apiVersion: v1
kind: Namespace
metadata:
  name: faroldoinvestimento
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: faroldoinvestimento
  name: faroldoinvestimento
spec:
  selector:
    matchLabels:
      app: faroldoinvestimento
  replicas: 2
  template:
    metadata:
      labels:
        app: faroldoinvestimento
    spec:
      containers:
        - name: faroldoinvestimento
          image: docker.io/lealssa/faroldoinvestimento:v0.8
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: faroldoinvestimento
  name: faroldoinvestimento
spec:
  type: ClusterIP
  ports:
    - port: 5678
      targetPort: 80
  selector:
    app: faroldoinvestimento
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: faroldoinvestimento
  name: faroldoinvestimento-tls-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
spec:
  rules:
    - host: www.faroldoinvestimento.com.br
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: faroldoinvestimento
                port:
                  number: 5678
  tls:
    - secretName: faroldoinvestimento-tls
      hosts:
        - www.faroldoinvestimento.com.br
