# Generated by Django 5.2.8 on 2025-11-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10)),
                ('notas', models.TextField(blank=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Simulacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montante_aplicado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('valor_no_vencimento', models.DecimalField(decimal_places=2, max_digits=15)),
                ('bruto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('liquido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('imposto_devido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('aliquota_ir', models.DecimalField(decimal_places=4, max_digits=5)),
                ('prazo_mes', models.IntegerField()),
                ('info', models.CharField(max_length=100)),
                ('taxa_real', models.DecimalField(decimal_places=4, max_digits=10)),
                ('inflacao_periodo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('dividido_no_prazo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('session_key', models.CharField(db_index=True, max_length=40)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
